### PR TITLE
review notes

### PR DESCRIPTION
**Pull request by OksanaFirtych**

### CODE REVIEW

**Review by Alicino88 — COMMENTED** [review]
Oksana this has been super helpful. One question I have is the following: I have added the map method inside the Work.js component and the data are now taken from an array inside the file itself. What if I wanted to have the contents in a separate file, should I create a json file, import it and use it?

**Comment by OksanaFirtych** [comment]
@Alicino88 map looks good, but in console you should see the React error about key. When you render elements by map you should ad uniq key property to element (https://adhithiravi.medium.com/why-do-i-need-keys-in-react-lists-dbb522188bbb you can read more about key and why you should use them in React. It's quite important)

About json. You can create the separate json or even just js file with export with an array. After that, you can import the array to any other file whenever you need it like you importing components from one file in another.

**Comment by Alicino88** [comment]
> 
> 
> @Alicino88 map looks good, but in console you should see the React error about key. When you render elements by map you should ad uniq key property to element (https://adhithiravi.medium.com/why-do-i-need-keys-in-react-lists-dbb522188bbb you can read more about key and why you should use them in React. It's quite important)
> 
> About json. You can create the separate json or even just js file with export with an array. After that, you can import the array to any other file whenever you need it like you importing components from one file in another.

I have added the key :-) also a bit of animations to make the website a bit more dynamic

**Comment by OksanaFirtych** [comment]
@Alicino88 looks good now!

**Pull request closed without merging**
